apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 240-integration-ace
  labels:
    type: software
    code: '240'
  annotations:
    displayName: Integration - App Connect
    description: GitOps deployment of App Connect for Cloud pak for Integration
    deployment-type/gitops: 'true'
spec:
  modules:
    - name: cp4i-dependency-management
      alias: cp4i-version-dependency
      version: v1.2.7
      variables:
        - name: cp4i_version
          value: '2022_2_1'
    - name: gitops-cp-ace
      alias: gitops-cp-ace
      version: v1.0.8
    - name: gitops-cp-ace-designer
      alias: gitops-cp-ace-designer
      version: v1.0.5
      dependencies:
        - name: namespace
          ref: cp4i-ace
      variables:
        - name: storage_class_4_couchdb
          alias: rwo_storage_class
          scope: global
        - name: storage_class_4_mapassist
          alias: rwx_storage_class
          scope: global
        - name: is_map_assist_required
          value: false
    - name: gitops-cp-catalogs
      alias: gitops-cp-catalogs
      version: v1.2.7
      variables:
        - name: entitlement_key
          scope: global
    - name: gitops-namespace
      alias: cp4i-ace
      version: v1.15.0
      variables:
        - name: name
          value: cp4i-ace
    - name: gitops-repo
      alias: gitops_repo
      version: v1.22.2
    - name: namespace
      alias: gitea_namespace
      version: v3.2.4
      variables:
        - name: name
          value: gitea
    - name: ocp-login
      alias: cluster
      version: v1.6.0
    - name: olm
      alias: olm
      version: v1.3.5
    - name: gitea
      alias: gitea
      version: v0.5.0
      dependencies:
        - id: namespace
          ref: gitea_namespace
    - name: sealed-secret-cert
      alias: sealed-secret-cert
      version: v1.0.1
    - name: util-clis
      version: v1.18.1
  variables:
    - name: rwo_storage_class
      type: string
      description: ReadWriteOnce access type Storage Class
      defaultValue: portworx-db2-rwo-sc
    - name: rwx_storage_class
      type: string
      description: ReadWriteMany access type Storage Class
      defaultValue: portworx-rwx-gp-sc
    - name: entitlement_key
      type: string
      description: >-
        The entitlement key used to access the CP4I images in the container
        registry. Visit https://myibm.ibm.com/products-services/containerlibrary
        to get the key
      sensitive: true
    - name: gitops_repo_host
      type: string
      description: The host for the git repository.
      defaultValue: ''
    - name: gitops_repo_type
      type: string
      description: The type of the hosted git repository (github or gitlab).
      defaultValue: ''
    - name: gitops_repo_org
      type: string
      description: The org/group where the git repository exists/will be provisioned.
      defaultValue: ''
    - name: gitops_repo_project
      type: string
      description: >-
        The project that will be used for the git repo. (Primarily used for
        Azure DevOps repos)
      defaultValue: ''
    - name: gitops_repo_username
      type: string
      description: The username of the user with access to the repository
      defaultValue: ''
    - name: gitops_repo_token
      type: string
      description: The personal access token used to access the repository
      defaultValue: ''
      sensitive: true
    - name: gitops_repo_repo
      type: string
      description: >-
        The short name of the repository (i.e. the part after the org/group
        name)
    - name: server_url
      type: string
      description: The url for the OpenShift api
    - name: cluster_login_token
      type: string
      description: Token used for authentication
      sensitive: true
  outputs:
    - name: entitlement_key
      sensitive: true
    - name: gitops_repo_token
      sensitive: true
    - name: cluster_login_token
      sensitive: true
