apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pwx-claim
  namespace: rook-nfs
spec:
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
