apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 230-integration-mq
  labels:
    type: software
    code: '230'
  annotations:
    displayName: Integration Platform
    description: >-
      Populates a GitOps repository with MQ component of the IBM Integration
      Platform
spec:
  modules:
    - name: gitops-cp-catalogs
      alias: gitops-cp-catalogs
      version: v1.2.1
      variables:
        - name: entitlement_key
          scope: global
    - name: gitops-cp-mq
      alias: gitops-cp-mq
      version: v1.1.5
    - name: gitops-cp-queue-manager
      alias: gitops-cp-queue-manager
      version: v1.0.4
      dependencies:
        - name: namespace
          ref: cp4i-mq
      variables:
        - name: qmgr_name
          value: QM1
        - name: qmgr_instance_name
          value: mq-instance
        - name: config_map
          value: oms-queue-config
        - name: storageclass
          alias: rwo_storage_class
          scope: global
    - name: gitops-namespace
      alias: cp4i-mq
      version: v1.11.2
      variables:
        - name: name
          value: cp4i-mq
    - name: ocp-login
      alias: cluster
      version: v1.2.12
    - name: olm
      alias: olm
      version: v1.3.2
    - name: sealed-secret-cert
      alias: sealed-secret-cert
      version: v1.0.1
    - name: gitops-repo
      alias: gitops_repo
      version: v1.16.0
    - name: cp4i-dependency-management
      version: v1.2.3
  variables:
    - name: entitlement_key
      type: string
      description: >-
        The entitlement key used to access the CP4I images in the container
        registry. Visit https://myibm.ibm.com/products-services/containerlibrary
        to get the key
      sensitive: true
    - name: rwo_storage_class
      type: string
      description: ReadWriteOnce access type Storage Class
      defaultValue: portworx-db2-rwo-sc
    - name: server_url
      type: string
      description: The url for the OpenShift api
    - name: cluster_login_token
      type: string
      description: Token used for authentication
      sensitive: true
    - name: gitops_repo_host
      type: string
      description: The host for the git repository.
    - name: gitops_repo_type
      type: string
      description: The type of the hosted git repository (github or gitlab).
    - name: gitops_repo_org
      type: string
      description: The org/group where the git repository exists/will be provisioned.
    - name: gitops_repo_repo
      type: string
      description: >-
        The short name of the repository (i.e. the part after the org/group
        name)
    - name: gitops_repo_username
      type: string
      description: The username of the user with access to the repository
    - name: gitops_repo_token
      type: string
      description: The personal access token used to access the repository
      sensitive: true
